Check if Gunicorn and Nginx config exists

diff --git a/addsite b/addsite
--- a/addsite
+++ b/addsite
@@ -5,6 +5,29 @@ DBPASS=`< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c12`
 SFTPPASS=`< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c12`
 ROOTDIR=/var/www/
 
+# Input site name
+echo -n "Enter your site name (spaces and special symbols are not allowed):"
+read SITENAME
+
+# Check if the /var/www/$SITENAME dir exists
+if [ -d "${ROOTDIR}${SITENAME}" ]; then
+    echo "Error: directory /var/www/$SITENAME already exists"
+    exit 1
+fi
+if [ -f "/etc/systemd/system/gunicorn_${SITENAME}.service" ]; then
+    echo "Error: Gunicorn config file '/etc/systemd/system/gunicorn_${SITENAME}.service' already exists. Try using different site name or delete the Gunicorn config file"
+    exit 1
+fi
+if [ -f "/etc/nginx/sites-available/${SITENAME}.conf" ]; then
+    echo "Error: Nginx config file '/etc/nginx/sites-available/${SITENAME}.conf' already exists. Try using different site name or delete the Gunicorn config file"
+    exit 1
+fi
+
+# Input domain name
+echo -n "Enter your domain name:"
+read DOMAIN
+
+
 while true
 do
 	echo "Select database server type:
@@ -30,18 +53,6 @@ if [[ $DBPACKAGE == "postgresql postgresql-contrib" ]]; then
     DBCONNECTOR="psycopg2-binary"
     DBENGINE="django.db.backends.postgresql_psycopg2"
     DBPORT="5432"
-fi
-
-# Input site name and domain name
-echo -n "Enter your site name (spaces and special symbols are not allowed):"
-read SITENAME
-echo -n "Enter your domain name:"
-read DOMAIN
-
-# Check if the /var/www/$SITENAME dir exists
-if [ -d "${ROOTDIR}${SITENAME}" ]; then
-    echo "Error: directory /var/www/$SITENAME already exists"
-    exit 1
 fi
 
 # Creating the working directory
@@ -112,7 +123,7 @@ echo "server {
         proxy_pass http://unix:/run/gunicorn_$SITENAME.sock;
     }
 }" > /etc/nginx/sites-available/$SITENAME.conf
-ln -s /etc/nginx/sites-available/$SITENAME.conf /etc/nginx/sites-enabled/$SITENAME.conf >> $HOMEDIR/deploy.log
+ln -sf /etc/nginx/sites-available/$SITENAME.conf /etc/nginx/sites-enabled/$SITENAME.conf >> $HOMEDIR/deploy.log
 systemctl restart nginx
 
 # Create Gunicorn config file
